name: epp
base: core24
version: "2.0.0"
summary: edit++ is a pluggable fork of Microsoft Edit
description: |
  edit++ is a fork of Microsoft Edit that adds a command registry, rebindable multi-key keybindings, a command palette, and a Lua plugin system.

  Disclaimer: This is an unofficial Snap and it is not endorsed by nor affiliated officially with Microsoft Corporation.

grade: stable
confinement: strict

apps:
  epp:
    command: bin/epp
    plugs:
      - home

parts:
  edit:
    source: https://github.com/microsoft/edit.git
    source-type: git
    plugin: rust
    build-packages:
      - build-essential
